### ISSUE TITLE
Several questions about running FACSvatar through Docker

### ISSUE THREAD

**Issue by Animixer** [NumesSanguis/FACSvatar-Blender#2]
Hi,

My first question is how do I use Docker to send my own .csv data to the Facsvatar Blender plugin?
Should I set up one container for the Bridge process, one for the FACStoBlend process and one for the Input process, using the Dockerfiles in the respective directories?

If yes, I assume the next step is to run main.py in all three containers?

Second question is can you help me fix the **ZeroMQError: Address already in use** I get when I run main.py in the Facstoblend container, as well as in the Bridge container:

**facsvatar_facstoblend**:

INFO:root:Current libzmq version is 4.3.2
INFO:root:Current  pyzmq version is 18.1.1
INFO:root:Publisher port is specified
INFO:root:Creating ZeroMQ context on: tcp://127.0.0.1:5572
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    facsvatar_messages = FACSvatarMessages(**vars(args))
  File "main.py", line 56, in __init__
    super().__init__(**kwargs)
  File "/app/process_facstoblend/facsvatarzeromq.py", line 73, in __init__
    self.pub_socket = FACSvatarSocket(self.zeromq_context(pub_ip, pub_port, zmq.PUB, pub_bind),
  File "/app/process_facstoblend/facsvatarzeromq.py", line 152, in zeromq_context
    socket.bind(url)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

**facsvatar_bridge**:

INFO:root:Current libzmq version is 4.3.2
INFO:root:Current  pyzmq version is 19.0.0
INFO:root:Publisher port is specified
INFO:root:Creating ZeroMQ context on: tcp://127.0.0.1:5571
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    facsvatar_messages = FACSvatarMessages(**vars(args))
  File "main.py", line 53, in __init__
    super().__init__(**kwargs)
  File "/app/process_bridge/facsvatarzeromq.py", line 73, in __init__
    self.pub_socket = FACSvatarSocket(self.zeromq_context(pub_ip, pub_port, zmq.PUB, pub_bind),
  File "/app/process_bridge/facsvatarzeromq.py", line 152, in zeromq_context
    socket.bind(url)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

[This issue](https://github.com/ipython/ipython/issues/6109) and [this issue](https://github.com/stan-dev/pystan/issues/142) seem to be related to this error. These discussions are too complicated for me, so your help is much appreciated.

Finally, I tried to run a container for the input process, but it did not start up. No logs are shown in the Docker dashboard so I have very little info on this.

**Comment by NumesSanguis** [comment]
Sorry for my late reply.

### 1st question
That's an interesting use-case. Currently, the folder "openface/default_clean" is copied into the Docker image at creation time. If you want to keep using Docker, you have 3 options:

1. Modify `docker-compose.yml` and add a `volumes:` to `facsvatar_facsfromcsv`. This would give the Docker container access to a folder on your computer.
2. (Easier if you change the .csv file sometimes) Put your files in the `openface` folder and rebuild the image.
3. Copy the file to your container.

Instructions for step 2 & 3 can be found here: https://facsvatar.readthedocs.io/en/latest/docker.html#docker-own-openface-csv-untested

### 2nd question
It seems that on your computer there are some programs that already use the default ports used by FACSvatar (5570-5574), or that you already have FACSvatar running in another container.

---

## Python env
If you're not comfortable with Docker, the above solutions might seem quite challenging. The Docker approach is to quickly get FACSvatar running on your system, so you can get an impression of what is possible. The other reason for using Docker is if you're already used to Docker and want to easily deploy FACSvatar on other PCs or are tired of having to open many terminals.

It seems in your case that you just want to get everything running and do a few manipulations. Therefore, I would suggest you to:
- Setup a Python environment (recommended with [Anaconda](https://anaconda.org/))
- Follow the setup instructions under FACSvatar modules: https://facsvatar.readthedocs.io/en/latest/defaultsetup.html#facsvatar-modules (ignore the Blender instructions, these are outdated with this new add-on)
- Run FACSvatar with these instructions: https://facsvatar.readthedocs.io/en/latest/firstrun.html#facsvatar-modules

Every module has extra parameters you can add to modify the behavior of the module. For all possible arguments, run: `python main.py --help`.
- For example, with your port issue, you can try `python main.py --pub_port 6670` to change the port to 6670 (make sure that if you change the `pub_port` of `input_facsfromcsv` to 6670, that the you run `process_bridge` module with `python main.py --sub_port 6670`. The port where a module publishes to, needs to match the port the next module subscribes to.
- For your 1st issue, you can include argument such as `--csv_folder` to change the location where the `input_facsfromcsv` looks for OpenFace outputted csv files (https://github.com/NumesSanguis/FACSvatar/blob/master/modules/input_facsfromcsv/main.py#L434-L447). 

Another advantage of the Python approach is the terminals will always show you the output, so you don't have to connect with a Docker container

**EDIT:** For setting up FACSvatar with Python, please check out this video: https://youtu.be/OOoXDfkn8fk?t=727
You can ignore the Blender part, however, because this add-on takes care of that.

**Comment by Animixer** [comment]
Thanks for your elaborate answer, and apologies for not responding to this.

At this point, I have my facsvatar setup working fine for single animations.
I'm not using docker, just the cmd terminals with conda envs and python, which indeed shows helpful error messages when something is out of the ordinary. So thanks for suggesting this :)

**Comment by NumesSanguis** [comment]
Great to hear this @Animixer ;)
